drop table if exists member CASCADE;

create table member
(
    member_id bigint generated by default as identity,
    username  varchar(10) not null unique,
    email     varchar(100) unique,
    password  varchar(20) not null,
    primary key (member_id)
);

drop table if exists todo CASCADE;

create table todo
(
    todo_id    bigint generated by default as identity,
    member_id  bigint       not null,
    content    varchar(100) not null,
    status     varchar(10)  not null default 'ISSUE',
    created_at TIMESTAMP             DEFAULT CURRENT_TIMESTAMP,
    primary key (todo_id),
    foreign key (member_id) references member (member_id)
);